name: LDBC SNB Business Intelligence Benchmark

on:
  # schedule:  # Disabled for fork
    #   - cron: "0 5 * * *"

  workflow_dispatch:
    inputs:
      scale_factor:
        description: 'Scale factor'
        required: true
        default: "1"
        type: choice
        options:
          - "1"
          - "10"
          - "30"
          - "100"

jobs:
  benchmark:
    name: business-intelligence-benchmark
    runs-on: lbug-self-hosted-benchmarking-xl
    if: false
    env:
      NUM_THREADS: 128
      GEN: Ninja
    steps:
      - name: Set env for scheduled run
        if: ${{ github.event_name == 'schedule' }}
        run: |
          echo "SCALE_FACTOR=1" >> $GITHUB_ENV

      - name: Set env for workflow dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "SCALE_FACTOR=${{ github.event.inputs.scale_factor }}" >> $GITHUB_ENV
    
      - name: Set environment variables
        run: |
          echo "LBUG_CSV_DIR=$CSV_DIR/bi-dataset/bi-sf${SCALE_FACTOR}-composite-projected-fk/graphs/csv/bi/composite-projected-fk/" >> $GITHUB_ENV
          echo "LBUG_DIR=$(pwd)" >> $GITHUB_ENV
          echo "LBUG_BUILD_PATH=$(pwd)/tools/python_api/build" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Build lbug
        run: |
          pip3 install -e tools/python_api/[dev]
          make python
    
      - name: Clone implementation
        uses: actions/checkout@v4
        with:
          repository: lbugdb/ldbc_snb_bi
          path: ldbc_snb_bi
          token: ${{ secrets.DOC_PUSH_TOKEN }}
    
      - name: Link substitution parameters
        working-directory: ldbc_snb_bi
        run: |
          rm -rf parameters
          ln -s $CSV_DIR/bi-dataset/ldbc-snb-bi-parameters-sf1-to-sf30000 parameters
    
      - name: Load database
        working-directory: ldbc_snb_bi/lbug
        run: |
          workflow-scripts/decompress-gz.sh
          workflow-scripts/load-database.sh
    
      - name: Run benchmark
        working-directory: ldbc_snb_bi/lbug
        run: workflow-scripts/benchmark.sh
    
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: LDBC-SNB-Business-Intelligence-results
          path: ldbc_snb_bi/lbug/output/

      - name: Report result to server
        working-directory: ldbc_snb_bi/lbug/
        run: |
          python3 workflow-scripts/report_results.py
