name: Build Java Lib
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      isNightly:
        type: boolean
        required: true
        default: false
env:
  PIP_BREAK_SYSTEM_PACKAGES: 1

jobs:
  build-linux-java-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: build
          key: core-build-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('CMakeLists.txt', 'src/**', 'extension/**', 'tools/**') }}
          restore-keys: |
            core-build-${{ runner.os }}-${{ runner.arch }}-

      - name: Update nightly version
        if: ${{ inputs.isNightly == true }}
        run: |
          python3 -m pip install packaging
          python3 update-nightly-build-version.py
        working-directory: scripts

      - name: Build Java lib for Linux
        run: |
          make GEN=Ninja java

      - uses: actions/upload-artifact@v4
        with:
          name: java-lib-linux-x86_64
          path: tools/java_api/build/liblbug_java_native*

  build-linux-java-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: build
          key: core-build-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('CMakeLists.txt', 'src/**', 'extension/**', 'tools/**') }}
          restore-keys: |
            core-build-${{ runner.os }}-${{ runner.arch }}-

      - name: Update nightly version
        if: ${{ inputs.isNightly == true }}
        run: |
          python3 -m pip install packaging
          python3 update-nightly-build-version.py
        working-directory: scripts

      - name: Build Java lib for Linux
        run: make GEN=Ninja java

      - uses: actions/upload-artifact@v4
        with:
          name: java-lib-linux-aarch64
          path: tools/java_api/build/liblbug_java_native*

  build-linux-java-armv8a:
    runs-on: lbug-self-hosted-testing
    if: false
    steps:
      - uses: actions/checkout@v4

      - name: Update nightly version
        if: ${{ inputs.isNightly == true }}
        run: |
          python3 -m pip install packaging
          python3 update-nightly-build-version.py
        working-directory: scripts

      - name: Build Java lib for Linux
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DBUILD_JAVA=TRUE -DBUILD_SHELL=FALSE ..
          make -j$(nproc)
    
      - name: Rename artifact
        run: |
          mv tools/java_api/build/liblbug_java_native.so_linux_arm64 tools/java_api/build/liblbug_java_native.so_android_arm64
      
      - uses: actions/upload-artifact@v4
        with:
          name: java-lib-android-armv8a
          path: tools/java_api/build/liblbug_java_native*

  build-mac-java-arm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: build
          key: core-build-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('CMakeLists.txt', 'src/**', 'extension/**', 'tools/**') }}
          restore-keys: |
            core-build-${{ runner.os }}-${{ runner.arch }}-

      - name: Update nightly version
        if: ${{ inputs.isNightly == true }}
        run: |
          pip3 install packaging
          python3 update-nightly-build-version.py
        working-directory: scripts

      - name: Build Java lib for Apple Silicon
        run: |
          arch -arm64 env JAVA_HOME=$(/usr/libexec/java_home) make GEN=Ninja java
        env:
          MACOSX_DEPLOYMENT_TARGET: 11.0
          ARCHFLAGS: "-arch arm64"

      - uses: actions/upload-artifact@v4
        with:
          name: java-lib-osx-arm64
          path: tools/java_api/build/liblbug_java_native*

  build-windows-java:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: build
          key: core-build-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('CMakeLists.txt', 'src/**', 'extension/**', 'tools/**') }}
          restore-keys: |
            core-build-${{ runner.os }}-${{ runner.arch }}-

      - name: Update nightly version
        if: ${{ inputs.isNightly == true }}
        run: |
          pip3 install packaging
          python3 update-nightly-build-version.py
        working-directory: ./scripts

      - name: Build Java lib for Windows
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          make GEN=Ninja java

      - uses: actions/upload-artifact@v4
        with:
          name: java-lib-win-x86_64
          path: tools/java_api/build/liblbug_java_native*