name: LDBC Fintech Benchmark

on:
  # schedule:  # Disabled for fork
    #   - cron: "0 5 * * *"

  workflow_dispatch:
    inputs:
      scale_factor:
        description: 'Scale factor'
        required: true
        default: "1"
        type: choice
        options:
          - "1"
          - "10"

jobs:
  benchmark:
    name: ldbc-fintech-benchmark
    runs-on: lbug-self-hosted-benchmarking-xl
    if: false
    env:
      NUM_THREADS: 128
      GEN: Ninja
    steps:
      - name: Set env for scheduled run
        if: ${{ github.event_name == 'schedule' }}
        run: |
          echo "SCALE_FACTOR=1" >> $GITHUB_ENV

      - name: Set env for workflow dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "SCALE_FACTOR=${{ github.event.inputs.scale_factor }}" >> $GITHUB_ENV

      - name: Set checkout dir
        run: |
          echo "LBUG_DIR=$(pwd)" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Build lbug
        run: |
          pip3 install -e tools/python_api/[dev]
          make python
          make java
    
      - name: Clone implementation
        uses: actions/checkout@v4
        with:
          repository: lbugdb/ldbc_finbench_transaction_impls
          token: ${{ secrets.DOC_PUSH_TOKEN }}
          path: ldbc_finbench_transaction_impls
      
      - name: Update implementation
        working-directory: ldbc_finbench_transaction_impls
        run: |
          ln -s $LBUG_DIR/tools/java_api/build/lbug_java.jar lbug/src/main/resources/lbug_java.jar
          ln -s $LBUG_DIR/tools/python_api/build/lbug lbug/scripts/lbug
          mkdir -p lbug/src/main/resources/data
          ln -s $CSV_DIR/finbench-datasets/sf${SCALE_FACTOR} lbug/src/main/resources/data/sf${SCALE_FACTOR}
          mvn clean package -DskipTests

      - name: Load data
        working-directory: ldbc_finbench_transaction_impls
        run: python3 lbug/scripts/import_data.py sf${SCALE_FACTOR}

      - name: Run benchmark
        working-directory: ldbc_finbench_transaction_impls/lbug
        run:
          java -cp target/lbug-0.1.0-alpha.jar:target/classes/lbug_java.jar org.ldbcouncil.finbench.driver.driver.Driver -P sf${SCALE_FACTOR}_finbench_benchmark.properties | tee LDBC-FinBench.log
     
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: LDBC-FinBench-results
          path: ldbc_finbench_transaction_impls/lbug/results/LDBC-FinBench-results.json

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: LDBC-FinBench-logs
          path: ldbc_finbench_transaction_impls/lbug/LDBC-FinBench.log
    
      - name: Report result to server
        working-directory: ldbc_finbench_transaction_impls
        run: |
          python3 lbug/scripts/report_results.py
