name: Publish Python Fork to PyPI

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      publish_to_pypi:
        description: "Publish to PyPI (not just test PyPI)?"
        type: boolean
        required: true
        default: false

env:
  PIP_BREAK_SYSTEM_PACKAGES: 1

jobs:
  package-python-sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: pip3 install uv

      - name: Package Python sdist
        run: python package_tar.py
        working-directory: scripts/pip-package

      - name: Upload tarball
        uses: actions/upload-artifact@v4
        with:
          name: python-sdist
          path: scripts/pip-package/*.tar.gz

  build-linux-wheels:
    needs: package-python-sdist
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux x86_64 build
          - platform: x86_64
            runner: ubuntu-latest
            os: linux
            manylinux: _2_28

          # Linux aarch64 build
          - platform: aarch64
            runner: ubuntu-22.04-arm
            os: linux
            manylinux: _2_28

          # macOS arm64 build
          - platform: arm64
            runner: macos-latest
            os: macos
            deployment-target: '11.0'

          # Windows amd64 build
          - platform: amd64
            runner: windows-2022
            os: windows

    env:
      CIBW_PLATFORM: ${{ matrix.os }}
      CIBW_BUILD: "cp313-*"
      CIBW_ARCHS: ${{ matrix.os == 'windows' && 'AMD64' || 'auto' }}
      CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.os == 'linux' && format('manylinux{0}', matrix.manylinux) || '' }}
      CIBW_MANYLINUX_AARCH64_IMAGE: ${{ matrix.os == 'linux' && format('manylinux{0}', matrix.manylinux) || '' }}
      CIBW_ENVIRONMENT_WINDOWS: DISTUTILS_USE_SDK=1 MSSdk=1
      CIBW_ENVIRONMENT_MACOS: ${{ matrix.os == 'macos' && format('MACOSX_DEPLOYMENT_TARGET={0}', matrix.deployment-target) || '' }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: build
          key: core-build-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('CMakeLists.txt', 'src/**', 'extension/**', 'tools/**') }}
          restore-keys: |
            core-build-${{ runner.os }}-${{ runner.arch }}-

      - name: Download sdist
        uses: actions/download-artifact@v4
        with:
          name: python-sdist
          path: scripts/pip-package/

      - name: Find sdist file
        shell: bash
        run: echo "SDIST_FILE=$(ls scripts/pip-package/*.tar.gz)" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        run: python -m pip install uv

      - name: Install cibuildwheel
        if: matrix.os != 'windows'
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install cibuildwheel

      - name: Build wheels on ${{ matrix.platform }} (Windows)
        if: matrix.os == 'windows'
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          pipx run --spec cibuildwheel cibuildwheel %SDIST_FILE% --output-dir scripts\pip-package\wheelhouse

      - name: Build wheels on ${{ matrix.platform }} (Linux/macOS)
        if: matrix.os != 'windows'
        shell: bash
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install cibuildwheel
          python -m cibuildwheel --output-dir scripts/pip-package/wheelhouse ${{ env.SDIST_FILE }}

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os == 'linux' && format('manylinux{0}', matrix.manylinux) || matrix.os }}-wheels-${{ matrix.platform }}
          path: ./scripts/pip-package/wheelhouse/*.whl

  deploy-python:
    permissions:
      id-token: write
    environment:
      name: pypi
    needs: build-linux-wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: macos-wheels-arm64
          path: dist

      - uses: actions/download-artifact@v4
        with:
          name: manylinux_2_28-wheels-x86_64
          path: dist

      - uses: actions/download-artifact@v4
        with:
          name: manylinux_2_28-wheels-aarch64
          path: dist

      - uses: actions/download-artifact@v4
        with:
          name: windows-wheels-amd64
          path: dist

      - uses: actions/download-artifact@v4
        with:
          name: python-sdist
          path: dist

      - name: List wheels
        run: ls -l dist/

      - name: Deploy to Test PyPI
        if: ${{ github.event_name != 'release' && github.event.inputs.publish_to_pypi != 'true' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Deploy to PyPI
        if: ${{ github.event_name == 'release' || github.event.inputs.publish_to_pypi == 'true' }}
        uses: pypa/gh-action-pypi-publish@release/v1

